import { withTenantTransaction } from "@/lib/auth/repository";
import { EvaluationDomainError } from "@/lib/evaluation/errors";

type Input={name?:string;roleDescription?:string;leadershipPriority?:number|string|null;systemAdministratorOperator?:boolean;active?:boolean};
function validate(input:Input,creating:boolean){
  if((creating||input.name!==undefined)&&(!input.name?.trim()||input.name.trim().length>120))throw new EvaluationDomainError("Appointment type name must contain 1-120 characters",422,"APPOINTMENT_TYPE_NAME_INVALID");
  if((creating||input.roleDescription!==undefined)&&(!input.roleDescription?.trim()||input.roleDescription.trim().length>1000))throw new EvaluationDomainError("Standard responsibilities must contain 1-1000 characters",422,"APPOINTMENT_TYPE_DESCRIPTION_INVALID");
  if(input.leadershipPriority!==undefined&&input.leadershipPriority!==null&&input.leadershipPriority!==""&&(!Number.isInteger(Number(input.leadershipPriority))||Number(input.leadershipPriority)<1||Number(input.leadershipPriority)>100))throw new EvaluationDomainError("Leadership priority must be between 1 and 100",422,"LEADERSHIP_PRIORITY_INVALID");
}
export async function createAppointmentType(tenantId:string,accountId:string,input:Input){validate(input,true);return withTenantTransaction(tenantId,accountId,async client=>{try{return(await client.query(`INSERT INTO appointment_types(tenant_id,name,role_description,leadership_priority,system_administrator_operator)VALUES($1,$2,$3,$4,$5)RETURNING *`,[tenantId,input.name!.trim(),input.roleDescription!.trim(),input.leadershipPriority===""||input.leadershipPriority==null?null:Number(input.leadershipPriority),input.systemAdministratorOperator===true])).rows[0]}catch(error:any){if(error?.code==="23505")throw new EvaluationDomainError("That appointment type already exists",409,"APPOINTMENT_TYPE_EXISTS");throw error}})}
export async function updateAppointmentType(tenantId:string,accountId:string,id:string,input:Input){validate(input,false);return withTenantTransaction(tenantId,accountId,async client=>{const current=(await client.query("SELECT * FROM appointment_types WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[tenantId,id])).rows[0];if(!current)throw new EvaluationDomainError("Appointment type not found",404,"APPOINTMENT_TYPE_NOT_FOUND");if(input.active===false){const used=(await client.query("SELECT 1 FROM appointments WHERE tenant_id=$1 AND appointment_type_id=$2 AND active LIMIT 1",[tenantId,id])).rows[0];if(used)throw new EvaluationDomainError("Deactivate positions using this type first",409,"APPOINTMENT_TYPE_IN_USE")};try{const leadershipPriority=input.leadershipPriority===undefined?current.leadership_priority:input.leadershipPriority===""||input.leadershipPriority===null?null:Number(input.leadershipPriority);const type=(await client.query(`UPDATE appointment_types SET name=COALESCE($3,name),role_description=COALESCE($4,role_description),leadership_priority=$5,system_administrator_operator=COALESCE($6,system_administrator_operator),active=COALESCE($7,active),updated_at=clock_timestamp()WHERE tenant_id=$1 AND id=$2 RETURNING *`,[tenantId,id,input.name?.trim(),input.roleDescription?.trim(),leadershipPriority,input.systemAdministratorOperator,input.active])).rows[0];await client.query(`UPDATE appointments SET title=$3,role_description=$4 WHERE tenant_id=$1 AND appointment_type_id=$2`,[tenantId,id,type.name,type.role_description]);return type}catch(error:any){if(error?.code==="23505")throw new EvaluationDomainError("That appointment type already exists",409,"APPOINTMENT_TYPE_EXISTS");throw error}})}
