version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Male
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
        update-types: [minor, patch]
    labels: [dependencies, security-review-required]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, security-review-required]
