"use client";
import { useState, type ReactNode } from "react";
import { Download, FileText, ShieldCheck, WifiOff } from "lucide-react";
import { OperationalReportForm } from "./OperationalReportForm";
import { TrainingModeControl } from "./TrainingModeControl";

type FormalReport={full_name:string;personnel_code:string;cycle_name:string;cycle_type:string;score_percentage:number;status:string;public_comments:Array<{body:string}>;ratings:Array<{criterion:string;rating:number}>};
export function ReportingDashboard(){const[id,setId]=useState("");const[report,setReport]=useState<FormalReport|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
async function load(){setBusy(true);setError("");try{const response=await fetch(`/api/reports/formal/${encodeURIComponent(id)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setReport(data.report);}catch(e){setError(e instanceof Error?e.message:"Unable to load report");}finally{setBusy(false)}}
return <><TrainingModeControl/><main className="mx-auto min-h-screen max-w-7xl p-4 sm:p-6 lg:p-10"><header className="mb-8"><p className="text-sm font-semibold uppercase tracking-widest text-cyan-400">Performance Tracker</p><h1 className="mt-2 text-3xl font-bold text-white sm:text-4xl">Reports and performance overview</h1><p className="mt-2 max-w-2xl text-slate-400">Operational reporting contains no numerical ratings. Formal reports show approved performance information and exclude every restricted supervisory comment.</p></header>
<section className="grid gap-4 md:grid-cols-3"><Metric icon={<FileText/>} label="Operational cadence" value="4 report types"/><Metric icon={<ShieldCheck/>} label="Report privacy" value="Restricted excluded"/><Metric icon={<WifiOff/>} label="Offline access" value="UI shell only"/></section>
<section className="mt-8 rounded-2xl border border-slate-700 bg-slate-900 p-5"><label htmlFor="appraisal-id" className="text-sm font-semibold text-slate-200">Appraisal ID</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="appraisal-id" value={id} onChange={e=>setId(e.target.value)} className="min-h-12 flex-1 rounded-xl border border-slate-600 bg-slate-950 px-4 text-white" placeholder="Enter an authorized appraisal ID"/><button onClick={load} disabled={!id||busy} className="min-h-12 rounded-xl bg-cyan-500 px-6 font-bold text-slate-950 disabled:opacity-50">{busy?"Loading...":"Open report"}</button></div>{error?<p role="alert" className="mt-3 text-sm text-rose-400">{error}</p>:null}</section>
{report?<section className="mt-6 rounded-2xl border border-slate-700 bg-slate-900 p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm text-slate-400">{report.cycle_name} - {report.cycle_type}</p><h2 className="text-2xl font-bold">{report.full_name}</h2><p className="text-slate-400">{report.personnel_code}</p></div><div className="text-left sm:text-right"><p className="text-4xl font-bold text-cyan-400">{report.score_percentage}%</p><p className="text-sm text-slate-400">{report.status}</p></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><ReportList title="Final ratings" items={report.ratings.map(r=>`${r.criterion}: ${r.rating}/5`)}/><ReportList title="Member-visible comments" items={report.public_comments.map(c=>c.body)}/></div>{report.cycle_type==="QUARTERLY"?<a href={`/api/reports/formal/${encodeURIComponent(id)}/pdf`} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 font-bold text-slate-950"><Download className="h-5 w-5"/>Download printable PDF</a>:null}</section>:null}<OperationalReportForm/></main></>}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <article className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-950 text-cyan-400">{icon}</div><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-white">{value}</p></article>}
function ReportList({title,items}:{title:string;items:string[]}){return <div><h3 className="font-bold text-white">{title}</h3><ul className="mt-3 space-y-2">{items.length?items.map((item,index)=><li key={`${item}-${index}`} className="rounded-xl bg-slate-950 p-3 text-sm text-slate-300">{item}</li>):<li className="text-sm text-slate-500">None recorded</li>}</ul></div>}
