"use client";

import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";

type NodeDraft={clientId:string;parentClientId:string;nodeType:"OTHER";levelNumber:number|string;name:string;code:string};
const field="mt-2 min-h-12 w-full rounded-xl border border-slate-600 bg-slate-950 px-3";

export function InitialSetupWizard({onComplete}:{onComplete:()=>void}){
 const[step,setStep]=useState(1);const[storedNodes,setNodes]=useState<NodeDraft[]>([]);const nodes=storedNodes.map(node=>({...node,levelNumber:node.levelNumber??1}));const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 function addNode(){setNodes(v=>[...v,{clientId:crypto.randomUUID(),parentClientId:"ROOT",nodeType:"OTHER",levelNumber:Math.min(Number(v.at(-1)?.levelNumber??0)+1,10),name:"",code:""}])}
 function updateNode(id:string,key:keyof NodeDraft,value:string){const normalized=key==="levelNumber"?Number(value):value;setNodes(v=>v.map(n=>n.clientId===id?{...n,[key]:normalized}:n))}
 async function submit(form:HTMLFormElement){setBusy(true);setMsg("");const data=Object.fromEntries(new FormData(form));const structured=nodes.map((node,index)=>{const level=Number(node.levelNumber);if(level===1)return{...node,levelNumber:level,parentClientId:"ROOT"};const parent=[...nodes.slice(0,index)].reverse().find(candidate=>Number(candidate.levelNumber)===level-1);return{...node,levelNumber:level,parentClientId:parent?.clientId??""}});if(structured.some(node=>node.levelNumber>1&&!node.parentClientId)){setMsg("Each entry below Level 1 must follow an entry from the level immediately above it.");setBusy(false);setStep(2);return}const response=await fetch("/api/installation/bootstrap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,nodes:structured})});const body=await response.json().catch(()=>({}));if(response.ok)onComplete();else setMsg(body.error??"Setup failed");setBusy(false)}
 return <main className="mx-auto min-h-screen max-w-3xl p-4 py-10"><form onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}} className="rounded-2xl border border-slate-700 bg-slate-900 p-6">
  <p className="text-sm font-bold uppercase tracking-widest text-cyan-400">Performance Tracker · Initial setup</p><h1 className="mt-2 text-3xl font-bold">Create your organization</h1><p className="mt-2 text-slate-300">Technician setup · Step {step} of 4. This page closes after creation.</p>
  <div className={step===1?"mt-7 space-y-4":"hidden"}><h2 className="text-xl font-bold">1. Organization identity</h2><label className="block">Organization name<input name="organizationName" required className={field}/></label><label className="block">Organization code<input name="organizationCode" required className={field}/></label><label className="block">Timezone<input name="timezone" defaultValue="Indian/Maldives" required className={field}/></label></div>
  <div className={step===2?"mt-7":"hidden"}><h2 className="text-xl font-bold">2. Organizational structure</h2><p className="mt-2 text-slate-300">Enter each section or structural entry. Level 1 is highest, level numbers may repeat, and the maximum depth is Level 10.</p><div className="mt-4 space-y-4">{nodes.map((n,i)=><section key={n.clientId} className="rounded-xl border border-slate-700 p-4"><div className="flex items-start justify-between gap-4"><label className="block flex-1">Level number<input aria-label={`Level number for entry ${i+1}`} type="number" min={1} max={10} value={n.levelNumber} onChange={e=>updateNode(n.clientId,"levelNumber",String(Math.max(1,Math.min(10,Number(e.target.value)||1))))} required className={field}/></label><button type="button" aria-label={`Remove structure entry ${i+1}`} onClick={()=>setNodes(v=>v.filter(x=>x.clientId!==n.clientId))} className="mt-7 min-h-12 min-w-12"><Trash2/></button></div><label className="mt-3 block">Level name<input value={n.name} onChange={e=>updateNode(n.clientId,"name",e.target.value)} placeholder="For example: Finance Section" required={step===2} className={field}/></label><label className="mt-3 block">Level code<input value={n.code} onChange={e=>updateNode(n.clientId,"code",e.target.value)} placeholder="For example: FIN" required={step===2} className={field}/></label></section>)}</div><button type="button" onClick={addNode} className="mt-4 flex min-h-12 items-center gap-2 rounded-xl border border-cyan-500 px-4"><Plus/>Add another structural entry</button><p className="mt-3 text-sm text-slate-400">{nodes.length} entries across {new Set(nodes.map(node=>node.levelNumber)).size} of 10 possible levels</p></div>
  <div className={step===3?"mt-7 space-y-4":"hidden"}><h2 className="text-xl font-bold">3. System Authorizer</h2><p className="text-slate-300">Enter the organization’s actual leadership title. System authorization is assigned independently of the appointment title.</p><label className="block">Name<input name="authorizerName" required className={field}/></label><label className="block">Grade or designation<input name="authorizerRank" required className={field}/></label><label className="block">Authorizer appointment<input name="authorizerAppointment" placeholder="For example: Director General" required className={field}/></label><label className="block">Pilot login ID<input name="authorizerLogin" required className={field}/></label><label className="block">Password (minimum 12 characters)<input name="authorizerPassword" type="password" minLength={12} required className={field}/></label></div>
  <div className={step===4?"mt-7 space-y-4":"hidden"}><h2 className="text-xl font-bold">4. Dedicated System Administrator</h2><p className="text-slate-300">This is a separate administrative account. It remains disabled until the System Authorizer activates the organization.</p><label className="block">Administrator login ID<input name="adminLogin" required className={field}/></label><label className="block">Administrator password (minimum 12 characters)<input name="adminPassword" type="password" minLength={12} required className={field}/></label><div className="rounded-xl border border-amber-600/60 bg-amber-950/30 p-4 text-amber-100">Creating the organization permanently closes public initial setup on this installation.</div></div>
  {msg?<p role="alert" className="mt-5 text-amber-300">{msg}</p>:null}<div className="mt-7 flex gap-3">{step>1?<button type="button" onClick={()=>setStep(s=>s-1)} className="min-h-12 flex-1 rounded-xl border border-slate-600">Back</button>:null}{step<4?<button type="button" onClick={()=>setStep(s=>s+1)} className="min-h-12 flex-1 rounded-xl bg-cyan-500 font-bold text-slate-950">Continue</button>:<button disabled={busy} className="min-h-12 flex-1 rounded-xl bg-cyan-500 font-bold text-slate-950 disabled:opacity-60">{busy?"Creating...":"Create pending organization"}</button>}</div>
 </form></main>
}
