"use client";
import{useCallback,useEffect,useRef,useState}from"react";import{Bell}from"lucide-react";
type Notice={id:string;source:"GRIEVANCE"|"CORRECTION";title:string;body:string;deliver_at:string;read_at:string|null};
export function NotificationCenter(){const[items,setItems]=useState<Notice[]>([]),[open,setOpen]=useState(false);const seen=useRef(new Set<string>());
 const load=useCallback(async()=>{const response=await fetch("/api/notifications",{cache:"no-store"});if(!response.ok)return;const body=await response.json();const notices=(body.notifications??[])as Notice[];setItems(notices);if(typeof Notification!=="undefined"&&Notification.permission==="granted"){for(const notice of notices.filter(item=>!item.read_at&&!seen.current.has(item.id))){new Notification(notice.title,{body:"Open Performance Tracker to review this update.",tag:notice.id});seen.current.add(notice.id)}}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),60_000);return()=>clearInterval(timer)},[load]);
 const unread=items.filter(item=>!item.read_at).length;
 async function markRead(item:Notice){await fetch("/api/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,source:item.source})});await load()}
 return <div className="relative"><button type="button" aria-label={`Notifications${unread?` (${unread} unread)`:""}`} onClick={()=>setOpen(value=>!value)} className="relative grid h-12 w-12 place-items-center rounded-xl border border-slate-700"><Bell/>{unread?<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-rose-500 px-1 text-xs font-bold">{unread}</span>:null}</button>{open?<section className="absolute right-0 z-50 mt-2 w-[min(22rem,calc(100vw-2rem))] rounded-xl border border-slate-700 bg-slate-900 p-3 shadow-2xl"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Notifications</h2>{typeof Notification!=="undefined"&&Notification.permission==="default"?<button onClick={()=>void Notification.requestPermission()} className="min-h-10 rounded-lg border border-cyan-600 px-3 text-sm">Enable device alerts</button>:null}</div><div className="mt-3 max-h-96 space-y-2 overflow-y-auto">{items.length?items.map(item=><button key={`${item.source}:${item.id}`} onClick={()=>void markRead(item)} className={`block w-full rounded-lg border p-3 text-left ${item.read_at?"border-slate-800 text-slate-400":"border-cyan-700 bg-cyan-950/20"}`}><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-sm">{item.body}</span><time className="mt-2 block text-xs">{new Date(item.deliver_at).toLocaleString()}</time></button>):<p className="p-3 text-sm text-slate-400">No notifications.</p>}</div></section>:null}</div>}
