param([Parameter(Mandatory=$true)][string]$RetentionPolicyPath,[Parameter(Mandatory=$true)][string]$RetentionPolicySignaturePath,[Parameter(Mandatory=$true)][string]$RetentionPublicKey,[Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedRetentionPolicySha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedRetentionPublicKeySha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'Archive-review reminder input contains a reparse point'};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields){if((@($Record.PSObject.Properties.Name|Sort-Object)-join',')-ne(@($Fields|Sort-Object)-join',')){throw 'Retention policy schema is incomplete or contains unknown fields'}}
$policy=[IO.Path]::GetFullPath($RetentionPolicyPath);$signature=[IO.Path]::GetFullPath($RetentionPolicySignaturePath);$key=[IO.Path]::GetFullPath($RetentionPublicKey);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper);$inputs=@($policy,$signature,$key,$node,$helper);$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Archive-review reminder input not found: $path"};Assert-OrdinaryPath $path;$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  foreach($pair in @(@($policy,$ApprovedRetentionPolicySha256),@($key,$ApprovedRetentionPublicKeySha256),@($node,$ApprovedNodeExecutableSha256),@($helper,$ApprovedReleaseSigningHelperSha256))){if((Get-Sha256 $pair[0])-ne$pair[1].ToLowerInvariant()){throw 'Archive-review reminder trust fingerprint mismatch'}}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Archive-review reminder requires an authentic OpenJS Foundation Node.js runtime'}
  & $node $helper verify $policy $signature $key;if($LASTEXITCODE-ne0){throw 'Archive-review reminder rejected the retention-policy signature'}
  $record=Get-Content -LiteralPath $policy -Raw|ConvertFrom-Json;Assert-ExactSchema $record @('format','status','approvedAt','approvedBySid','custodianSid','releaseId','releaseCommit','host','archiveManifestSha256','archivePublicKeySha256','nextReviewAt','retainUntil','reviewIntervalDays','retentionYears','afterRetentionAction','automaticDeletion','retentionPublicKeySha256','containsSecrets')
  if($record.format-ne'performance-tracker-final-archive-retention-policy-v1'-or$record.status-ne'ACTIVE'-or$record.automaticDeletion-ne$false-or$record.containsSecrets-ne$false){throw 'Archive-review reminder requires an active redacted policy'}
  $due=[DateTimeOffset]::ParseExact([string]$record.nextReviewAt,'o',[Globalization.CultureInfo]::InvariantCulture);if($due.Offset-ne[TimeSpan]::Zero){throw 'Archive review due time must be UTC'}
  if([DateTimeOffset]::UtcNow-ge$due){Write-Error "Final archive integrity review is overdue for release $($record.releaseId); custodian $($record.custodianSid); due $($record.nextReviewAt)";exit 2}
  Write-Output "Final archive integrity review is current; next review due $($record.nextReviewAt)"
}finally{for($index=$streams.Count-1;$index-ge0;$index--){$streams[$index].Dispose()}}
