param(
 [Parameter(Mandatory=$true)][string]$PublicKeyFile,
 [Parameter(Mandatory=$true)][string]$OffHostDirectory,
 [string]$DatabaseUrl=$env:AUDIT_DATABASE_URL,
 [string]$LocalDirectory="audit-exports",
 [string]$PostgresBinDirectory="",
 [int]$LocalRetentionDays=7,
 [int]$OffHostRetentionDays=365,
 [switch]$AllowSameVolumeForRehearsal
)
$ErrorActionPreference="Stop";$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."));if(-not$DatabaseUrl){throw "AUDIT_DATABASE_URL is required"};if([string]::IsNullOrWhiteSpace($env:AUDIT_EXPORT_HMAC_KEY)-or$env:AUDIT_EXPORT_HMAC_KEY.Length-lt32){throw "AUDIT_EXPORT_HMAC_KEY is required"}
. (Join-Path $PSScriptRoot 'resolve-node-runtime.ps1');$node=Resolve-PerformanceTrackerNode -ProjectDirectory $project
$publicKey=[IO.Path]::GetFullPath($PublicKeyFile);if(-not(Test-Path -LiteralPath $publicKey)){throw "Audit export public key not found"};$local=[IO.Path]::GetFullPath((Join-Path $project $LocalDirectory));$offHost=[IO.Path]::GetFullPath($OffHostDirectory)
if($offHost-eq$local-or$offHost.StartsWith($local+[IO.Path]::DirectorySeparatorChar)){throw "Off-host audit storage must be separate from local export storage"};if(-not$AllowSameVolumeForRehearsal-and[IO.Path]::GetPathRoot($offHost)-eq[IO.Path]::GetPathRoot($local)){throw "Off-host audit retention must use a different volume or network share"}
New-Item -ItemType Directory -Force -Path $local,$offHost|Out-Null;$stamp=(Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ");$name="audit-ledger-$stamp";$staging=Join-Path $local "$name.partial";$completed=Join-Path $local $name;$destination=Join-Path $offHost $name;New-Item -ItemType Directory -Path $staging|Out-Null
$psql=if($PostgresBinDirectory){Join-Path ([IO.Path]::GetFullPath($PostgresBinDirectory)) "psql.exe"}else{"psql"};$crypto=Join-Path $PSScriptRoot "backup-crypto.mjs";$plain=Join-Path $staging "audit-ledger.jsonl";$encrypted="$plain.ptbk";$manifestPath=Join-Path $staging "manifest.json";$signaturePath="$manifestPath.hmac";$previousPgOptions=$env:PGOPTIONS
try{
 $tenantId=(& $psql --dbname=$DatabaseUrl --tuples-only --no-align --quiet --command="SELECT tenant_id FROM read_installation_identity()").Trim();if($LASTEXITCODE-ne0-or$tenantId-notmatch'^[0-9a-f-]{36}$'){throw "Installation tenant lookup failed"};$env:PGOPTIONS="-c app.tenant_id=$tenantId"
 $chain=(& $psql --dbname=$DatabaseUrl --tuples-only --no-align --quiet --command="SELECT valid::text||'|'||COALESCE(bad_audit_id::text,'') FROM verify_audit_hash_chain('$tenantId')").Trim();if($LASTEXITCODE-ne0-or$chain-notmatch'^true\|$'){throw "Database audit hash-chain verification failed: $chain"}
 $rows=@(& $psql --dbname=$DatabaseUrl --tuples-only --no-align --quiet --command="SELECT row_to_json(a)::text FROM audit_logs a WHERE tenant_id='$tenantId' ORDER BY id");if($LASTEXITCODE-ne0){throw "Audit ledger export failed"};[IO.File]::WriteAllLines($plain,$rows,(New-Object Text.UTF8Encoding($false)))
 $summary=(& $psql --dbname=$DatabaseUrl --tuples-only --no-align --quiet --command="SELECT count(*)::text||'|'||COALESCE(min(id)::text,'')||'|'||COALESCE(max(id)::text,'') FROM audit_logs WHERE tenant_id='$tenantId'").Trim().Split('|');if($LASTEXITCODE-ne0){throw "Audit ledger summary failed"}
 & $node $crypto encrypt $plain $encrypted $publicKey;if($LASTEXITCODE-ne0){throw "Audit ledger encryption failed"};Remove-Item -LiteralPath $plain;$object=Get-Item -LiteralPath $encrypted
 $manifest=[ordered]@{format="performance-tracker-audit-export-v1";createdAt=(Get-Date).ToUniversalTime().ToString("o");tenantId=$tenantId;rowCount=[long]$summary[0];firstAuditId=if($summary[1]){[long]$summary[1]}else{$null};lastAuditId=if($summary[2]){[long]$summary[2]}else{$null};databaseChainVerified=$true;encryptedObject=@{file=$object.Name;bytes=$object.Length;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $object.FullName).Hash.ToLowerInvariant()}}
 $manifest|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $manifestPath -Encoding utf8;& $node $crypto hmac $manifestPath $signaturePath;if($LASTEXITCODE-ne0){throw "Audit manifest signing failed"}
 Move-Item -LiteralPath $staging -Destination $completed;Copy-Item -LiteralPath $completed -Destination $destination -Recurse
 $copiedManifest=Get-Content -LiteralPath (Join-Path $destination "manifest.json") -Raw|ConvertFrom-Json;$copiedObject=Join-Path $destination $copiedManifest.encryptedObject.file;$actual=(Get-FileHash -Algorithm SHA256 -LiteralPath $copiedObject).Hash.ToLowerInvariant();if($actual-ne$copiedManifest.encryptedObject.sha256){throw "Off-host encrypted audit hash verification failed"};& $node $crypto verify-hmac (Join-Path $destination "manifest.json") (Join-Path $destination "manifest.json.hmac");if($LASTEXITCODE-ne0){throw "Off-host audit manifest signature verification failed"}
 Get-ChildItem -LiteralPath $local -Directory -Filter "audit-ledger-*"|Where-Object{$_.LastWriteTimeUtc-lt(Get-Date).ToUniversalTime().AddDays(-$LocalRetentionDays)}|Remove-Item -Recurse;Get-ChildItem -LiteralPath $offHost -Directory -Filter "audit-ledger-*"|Where-Object{$_.LastWriteTimeUtc-lt(Get-Date).ToUniversalTime().AddDays(-$OffHostRetentionDays)}|Remove-Item -Recurse
 $result=[ordered]@{status="SUCCESS";export=$name;rows=$manifest.rowCount;lastAuditId=$manifest.lastAuditId;offHostPath=$destination;verifiedAt=(Get-Date).ToUniversalTime().ToString("o")};Add-Content -LiteralPath (Join-Path $local "audit-export-operations.jsonl") -Value ($result|ConvertTo-Json -Compress) -Encoding utf8;$result|ConvertTo-Json -Compress
}catch{if(Test-Path -LiteralPath $staging){Remove-Item -LiteralPath $staging -Recurse};$failure=[ordered]@{status="FAILED";export=$name;failedAt=(Get-Date).ToUniversalTime().ToString("o");message=$_.Exception.Message};Add-Content -LiteralPath (Join-Path $local "audit-export-operations.jsonl") -Value ($failure|ConvertTo-Json -Compress) -Encoding utf8;throw}finally{$env:PGOPTIONS=$previousPgOptions}
