param(
  [Parameter(Mandatory=$true)][string]$InstallerApprovalPath,
  [Parameter(Mandatory=$true)][string]$InstallationReceiptPath,[Parameter(Mandatory=$true)][string]$InstallationReceiptSignaturePath,[Parameter(Mandatory=$true)][string]$ReceiptPublicKey,
  [Parameter(Mandatory=$true)][string]$AuditManifestPath,[Parameter(Mandatory=$true)][string]$AuditManifestSignaturePath,[Parameter(Mandatory=$true)][string]$AuditPublicKey,
  [Parameter(Mandatory=$true)][string]$CustodyHandoffPath,[Parameter(Mandatory=$true)][string]$CustodyHandoffSignaturePath,[Parameter(Mandatory=$true)][string]$SenderPublicKey,
  [Parameter(Mandatory=$true)][string]$CustodyOutcomePath,[Parameter(Mandatory=$true)][string]$CustodyOutcomeSignaturePath,[Parameter(Mandatory=$true)][string]$OutcomePublicKey,
  [Parameter(Mandatory=$true)][ValidateSet('RECEIVED','EXCEPTION')][string]$OutcomeType,
  [Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,
  [Parameter(Mandatory=$true)][string]$ClosureSigningPrivateKey,[Parameter(Mandatory=$true)][string]$ClosureSigningPublicKey,[Parameter(Mandatory=$true)][string]$ClosurePath,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerApprovalSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallationReceiptSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedAuditManifestSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyHandoffSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyOutcomeSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$')][string]$ExpectedReleaseId,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$ExpectedReleaseCommit,[Parameter(Mandatory=$true)][string]$ExpectedHost
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Deployment closure path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields,[string]$Label){if((@($Record.PSObject.Properties.Name|Sort-Object)-join',')-ne(@($Fields|Sort-Object)-join',')){throw "$Label schema is incomplete or contains unknown fields"}}
function Write-NewJson([string]$Path,$Value){$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$bytes=[Text.UTF8Encoding]::new($false).GetBytes(($Value|ConvertTo-Json -Depth 6));$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}
if([string]::IsNullOrWhiteSpace($env:RELEASE_SIGNING_KEY_PASSPHRASE)-or$env:RELEASE_SIGNING_KEY_PASSPHRASE.Length-lt20){throw 'RELEASE_SIGNING_KEY_PASSPHRASE is required for deployment closure signing'}
$approval=[IO.Path]::GetFullPath($InstallerApprovalPath);$receipt=[IO.Path]::GetFullPath($InstallationReceiptPath);$receiptSignature=[IO.Path]::GetFullPath($InstallationReceiptSignaturePath);$receiptKey=[IO.Path]::GetFullPath($ReceiptPublicKey);$manifest=[IO.Path]::GetFullPath($AuditManifestPath);$manifestSignature=[IO.Path]::GetFullPath($AuditManifestSignaturePath);$auditKey=[IO.Path]::GetFullPath($AuditPublicKey);$handoff=[IO.Path]::GetFullPath($CustodyHandoffPath);$handoffSignature=[IO.Path]::GetFullPath($CustodyHandoffSignaturePath);$senderKey=[IO.Path]::GetFullPath($SenderPublicKey);$outcome=[IO.Path]::GetFullPath($CustodyOutcomePath);$outcomeSignature=[IO.Path]::GetFullPath($CustodyOutcomeSignaturePath);$outcomeKey=[IO.Path]::GetFullPath($OutcomePublicKey);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper);$privateKey=[IO.Path]::GetFullPath($ClosureSigningPrivateKey);$publicKey=[IO.Path]::GetFullPath($ClosureSigningPublicKey);$closure=[IO.Path]::GetFullPath($ClosurePath);$closureSignature="$closure.sig.json"
$inputs=@($approval,$receipt,$receiptSignature,$receiptKey,$manifest,$manifestSignature,$auditKey,$handoff,$handoffSignature,$senderKey,$outcome,$outcomeSignature,$outcomeKey,$node,$helper,$privateKey,$publicKey)
foreach($path in $inputs){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Deployment closure input not found: $path"};Assert-OrdinaryPath $path}
if((Test-Path -LiteralPath $closure)-or(Test-Path -LiteralPath $closureSignature)){throw 'Deployment closure and signature must not already exist'}
$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  foreach($pair in @(@($approval,$ApprovedInstallerApprovalSha256),@($receipt,$ApprovedInstallationReceiptSha256),@($manifest,$ApprovedAuditManifestSha256),@($handoff,$ApprovedCustodyHandoffSha256),@($outcome,$ApprovedCustodyOutcomeSha256),@($node,$ApprovedNodeExecutableSha256),@($helper,$ApprovedReleaseSigningHelperSha256))){if((Get-Sha256 $pair[0])-ne$pair[1].ToLowerInvariant()){throw 'Deployment closure input fingerprint does not match independent approval'}}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Deployment closure requires an authentic OpenJS Foundation Node.js runtime'}
  foreach($triple in @(@($receipt,$receiptSignature,$receiptKey),@($manifest,$manifestSignature,$auditKey),@($handoff,$handoffSignature,$senderKey),@($outcome,$outcomeSignature,$outcomeKey))){& $node $helper verify $triple[0] $triple[1] $triple[2];if($LASTEXITCODE-ne0){throw 'Deployment closure evidence signature verification failed'}}
  try{$approvalRecord=Get-Content $approval -Raw|ConvertFrom-Json;$receiptRecord=Get-Content $receipt -Raw|ConvertFrom-Json;$manifestRecord=Get-Content $manifest -Raw|ConvertFrom-Json;$handoffRecord=Get-Content $handoff -Raw|ConvertFrom-Json;$outcomeRecord=Get-Content $outcome -Raw|ConvertFrom-Json}catch{throw 'Deployment closure evidence is not valid JSON'}
  Assert-ExactSchema $approvalRecord @('format','approvedBySid','approvedAtUtc','expiresAtUtc','installerSha256','signingCertificateThumbprint','timestampCertificateThumbprint','version','releaseCommit','releaseId','compilerSha256','signToolSha256','releasePublicKeySha256','nodeRuntimeSha256','launcherSha256','verifierSha256','aclHelperSha256','releaseSigningHelperSha256','packageCustodians') 'Installer approval'
  Assert-ExactSchema $receiptRecord @('format','status','completedAt','host','operatorSid','releaseId','releaseCommit','releaseManifestSha256','migrationEvidenceSha256','applicationTaskName','applicationTaskState','serviceAccountSid','healthStatus','healthEndpoint','aclVerificationSha256','receiptPublicKeySha256','containsSecrets') 'Installation receipt'
  Assert-ExactSchema $manifestRecord @('format','status','createdAt','releaseId','releaseCommit','host','receiptSha256','receiptPublicKeySha256','runtime','files','containsSecrets') 'Audit manifest'
  Assert-ExactSchema $handoffRecord @('format','status','transferId','handedOffAt','senderSid','receiverSid','transferMethod','manifestSha256','bundlePublicKeySha256','releaseId','releaseCommit','host','custodyPublicKeySha256','containsSecrets') 'Custody handoff'
  $outcomeFields=if($OutcomeType-eq'RECEIVED'){@('format','status','transferId','receivedAt','senderSid','receiverSid','transferMethod','handoffSha256','manifestSha256','bundleVerified','releaseId','releaseCommit','host','receiverPublicKeySha256','containsSecrets')}else{@('format','status','transferId','exceptionAt','handedOffAt','acknowledgementHours','dueAt','reason','authorizedCustodianSid','senderSid','receiverSid','transferMethod','handoffSha256','manifestSha256','releaseId','releaseCommit','host','exceptionPublicKeySha256','receiptPresent','containsSecrets')};Assert-ExactSchema $outcomeRecord $outcomeFields 'Custody outcome'
  if($approvalRecord.format-ne'performance-tracker-install-approval-v1'-or$approvalRecord.installerSha256-ne$ApprovedInstallerSha256.ToLowerInvariant()){throw 'Installer approval is invalid or binds another installer'}
  if($receiptRecord.format-ne'performance-tracker-production-installation-receipt-v1'-or$receiptRecord.status-ne'PASS'-or$manifestRecord.format-ne'performance-tracker-installation-audit-bundle-v1'-or$manifestRecord.status-ne'PASS'-or$handoffRecord.format-ne'performance-tracker-audit-custody-handoff-v1'-or$handoffRecord.status-ne'HANDED_OFF'){throw 'Deployment closure requires passed installation and audit evidence'}
  $expectedOutcomeFormat=if($OutcomeType-eq'RECEIVED'){'performance-tracker-audit-custody-receipt-v1'}else{'performance-tracker-audit-custody-exception-v1'};if($outcomeRecord.format-ne$expectedOutcomeFormat-or$outcomeRecord.status-ne$OutcomeType){throw 'Custody outcome type does not match its record'}
  foreach($record in @($approvalRecord,$receiptRecord,$manifestRecord,$handoffRecord,$outcomeRecord)){if($record.releaseId-ne$ExpectedReleaseId-or$record.releaseCommit-ne$ExpectedReleaseCommit.ToLowerInvariant()){throw 'Deployment closure evidence belongs to another release'}}
  foreach($record in @($receiptRecord,$manifestRecord,$handoffRecord,$outcomeRecord)){if($record.host-ne$ExpectedHost){throw 'Deployment closure evidence belongs to another host'}}
  if($manifestRecord.receiptSha256-ne$ApprovedInstallationReceiptSha256.ToLowerInvariant()-or$handoffRecord.manifestSha256-ne$ApprovedAuditManifestSha256.ToLowerInvariant()-or$outcomeRecord.manifestSha256-ne$ApprovedAuditManifestSha256.ToLowerInvariant()-or$outcomeRecord.handoffSha256-ne$ApprovedCustodyHandoffSha256.ToLowerInvariant()-or$outcomeRecord.transferId-ne$handoffRecord.transferId){throw 'Deployment closure evidence chain is not internally linked'}
  if($OutcomeType-eq'RECEIVED'-and$outcomeRecord.bundleVerified-ne$true){throw 'Received custody outcome did not verify the bundle'};if($OutcomeType-eq'EXCEPTION'-and$outcomeRecord.receiptPresent-ne$false){throw 'Exception custody outcome conflicts with a receipt'}
  $record=[ordered]@{format='performance-tracker-deployment-closure-v1';status='CLOSED';closedAt=[DateTimeOffset]::UtcNow.ToString('o');closedBySid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;releaseId=$ExpectedReleaseId;releaseCommit=$ExpectedReleaseCommit.ToLowerInvariant();host=$ExpectedHost;installerSha256=$ApprovedInstallerSha256.ToLowerInvariant();installerApprovalSha256=$ApprovedInstallerApprovalSha256.ToLowerInvariant();installationReceiptSha256=$ApprovedInstallationReceiptSha256.ToLowerInvariant();auditManifestSha256=$ApprovedAuditManifestSha256.ToLowerInvariant();custodyHandoffSha256=$ApprovedCustodyHandoffSha256.ToLowerInvariant();custodyTransferId=$handoffRecord.transferId;custodyOutcomeType=$OutcomeType;custodyOutcomeSha256=$ApprovedCustodyOutcomeSha256.ToLowerInvariant();closurePublicKeySha256=Get-Sha256 $publicKey;containsSecrets=$false}
  try{Write-NewJson $closure $record;& $node $helper sign $closure $privateKey $closureSignature;if($LASTEXITCODE-ne0){throw 'Deployment closure signing failed'};& $node $helper verify $closure $closureSignature $publicKey;if($LASTEXITCODE-ne0){throw 'Deployment closure signature verification failed'}}catch{Remove-Item -LiteralPath $closure,$closureSignature -Force -ErrorAction SilentlyContinue;throw}
}finally{for($index=$streams.Count-1;$index-ge0;$index--){$streams[$index].Dispose()}}
Write-Output "Signed deployment closure record: $closure"
Write-Output "Deployment closure SHA-256: $(Get-Sha256 $closure)"

