param(
  [Parameter(Mandatory=$true)][string]$RetentionPolicyPath,[Parameter(Mandatory=$true)][string]$RetentionPolicySignaturePath,[Parameter(Mandatory=$true)][string]$RetentionPublicKey,
  [Parameter(Mandatory=$true)][string]$ArchiveVerifier,[Parameter(Mandatory=$true)][string]$VerificationArgumentsPath,
  [Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,
  [Parameter(Mandatory=$true)][string]$ReviewSigningPrivateKey,[Parameter(Mandatory=$true)][string]$ReviewSigningPublicKey,[Parameter(Mandatory=$true)][string]$ReviewPath,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedRetentionPolicySha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedRetentionPublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedArchiveVerifierSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedVerificationArgumentsSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Archive-review path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields,[string]$Label){if((@($Record.PSObject.Properties.Name|Sort-Object)-join',')-ne(@($Fields|Sort-Object)-join',')){throw "$Label schema is incomplete or contains unknown fields"}}
function Read-UtcTimestamp([string]$Value,[string]$Label){try{$parsed=[DateTimeOffset]::ParseExact($Value,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw "$Label must use round-trip UTC format"};if($parsed.Offset-ne[TimeSpan]::Zero){throw "$Label must be UTC"};$parsed}
function Write-NewJson([string]$Path,$Value){$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$bytes=[Text.UTF8Encoding]::new($false).GetBytes(($Value|ConvertTo-Json -Depth 6));$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}
if([string]::IsNullOrWhiteSpace($env:RELEASE_SIGNING_KEY_PASSPHRASE)-or$env:RELEASE_SIGNING_KEY_PASSPHRASE.Length-lt20){throw 'RELEASE_SIGNING_KEY_PASSPHRASE is required for signed archive review evidence'}
$policy=[IO.Path]::GetFullPath($RetentionPolicyPath);$policySignature=[IO.Path]::GetFullPath($RetentionPolicySignaturePath);$policyKey=[IO.Path]::GetFullPath($RetentionPublicKey);$verifier=[IO.Path]::GetFullPath($ArchiveVerifier);$arguments=[IO.Path]::GetFullPath($VerificationArgumentsPath);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper);$privateKey=[IO.Path]::GetFullPath($ReviewSigningPrivateKey);$publicKey=[IO.Path]::GetFullPath($ReviewSigningPublicKey);$review=[IO.Path]::GetFullPath($ReviewPath);$reviewSignature="$review.sig.json"
$inputs=@($policy,$policySignature,$policyKey,$verifier,$arguments,$node,$helper,$privateKey,$publicKey);foreach($path in $inputs){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Archive-review input not found: $path"};Assert-OrdinaryPath $path}
if((Test-Path -LiteralPath $review)-or(Test-Path -LiteralPath $reviewSignature)){throw 'Archive integrity review and signature must not already exist'}
if($privateKey-eq$review-or$privateKey-eq$reviewSignature){throw 'Archive-review private key must remain separate from review evidence'}
$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  foreach($pair in @(@($policy,$ApprovedRetentionPolicySha256),@($policyKey,$ApprovedRetentionPublicKeySha256),@($verifier,$ApprovedArchiveVerifierSha256),@($arguments,$ApprovedVerificationArgumentsSha256),@($node,$ApprovedNodeExecutableSha256),@($helper,$ApprovedReleaseSigningHelperSha256))){if((Get-Sha256 $pair[0])-ne$pair[1].ToLowerInvariant()){throw 'Archive-review trust input fingerprint does not match independent approval'}}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Archive review requires an authentic OpenJS Foundation Node.js runtime'}
  & $node $helper verify $policy $policySignature $policyKey;if($LASTEXITCODE-ne0){throw 'Retention-policy signature verification failed'}
  try{$policyRecord=Get-Content -LiteralPath $policy -Raw|ConvertFrom-Json;$verificationRecord=Get-Content -LiteralPath $arguments -Raw|ConvertFrom-Json}catch{throw 'Archive-review control evidence is not valid JSON'}
  $policyFields=@('format','status','approvedAt','approvedBySid','custodianSid','releaseId','releaseCommit','host','archiveManifestSha256','archivePublicKeySha256','nextReviewAt','retainUntil','reviewIntervalDays','retentionYears','afterRetentionAction','automaticDeletion','retentionPublicKeySha256','containsSecrets');Assert-ExactSchema $policyRecord $policyFields 'Retention policy'
  if($policyRecord.format-ne'performance-tracker-final-archive-retention-policy-v1'-or$policyRecord.status-ne'ACTIVE'-or$policyRecord.containsSecrets-ne$false-or$policyRecord.automaticDeletion-ne$false-or$policyRecord.retentionPublicKeySha256-ne$ApprovedRetentionPublicKeySha256.ToLowerInvariant()){throw 'Archive review requires an active, redacted retention policy'}
  $approvedAt=Read-UtcTimestamp ([string]$policyRecord.approvedAt) 'Policy approval';$dueAt=Read-UtcTimestamp ([string]$policyRecord.nextReviewAt) 'Policy review';$retainUntil=Read-UtcTimestamp ([string]$policyRecord.retainUntil) 'Retention deadline';if($dueAt-le$approvedAt-or$retainUntil-le$approvedAt-or[DateTimeOffset]::UtcNow-gt$retainUntil){throw 'Archive retention policy chronology is invalid or expired'}
  $argumentFields=@('ArchiveDirectory','NodeExecutable','ExternalReleaseSigningHelper','ApprovedVerifierSha256','ApprovedManifestSha256','ApprovedArchivePublicKeySha256','ApprovedNodeExecutableSha256','ApprovedExternalSigningHelperSha256','ExpectedOutcomeType','ApprovedClosureSha256','ApprovedClosurePublicKeySha256','ApprovedInstallerApprovalSha256','ApprovedInstallerSha256','ApprovedInstallationReceiptSha256','ApprovedAuditManifestSha256','ApprovedCustodyHandoffSha256','ApprovedCustodyOutcomeSha256','ExpectedReleaseId','ExpectedReleaseCommit','ExpectedHost');Assert-ExactSchema $verificationRecord $argumentFields 'Archive verification arguments'
  if($verificationRecord.ApprovedManifestSha256-ne$policyRecord.archiveManifestSha256-or$verificationRecord.ApprovedArchivePublicKeySha256-ne$policyRecord.archivePublicKeySha256-or$verificationRecord.ExpectedReleaseId-ne$policyRecord.releaseId-or$verificationRecord.ExpectedReleaseCommit-ne$policyRecord.releaseCommit-or$verificationRecord.ExpectedHost-ne$policyRecord.host){throw 'Archive verification arguments do not match the retention policy'}
  $verifyArgs=@{};foreach($field in $argumentFields){$verifyArgs[$field]=$verificationRecord.$field};if([IO.Path]::GetFullPath([string]$verifyArgs.NodeExecutable)-ne$node-or[IO.Path]::GetFullPath([string]$verifyArgs.ExternalReleaseSigningHelper)-ne$helper){throw 'Archive verification arguments select unapproved executable trust inputs'}
  & $verifier @verifyArgs
  $now=[DateTimeOffset]::UtcNow;$record=[ordered]@{format='performance-tracker-final-archive-integrity-review-v1';status='PASS';reviewedAt=$now.ToString('o');reviewedBySid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;custodianSid=$policyRecord.custodianSid;releaseId=$policyRecord.releaseId;releaseCommit=$policyRecord.releaseCommit;host=$policyRecord.host;archiveManifestSha256=$policyRecord.archiveManifestSha256;retentionPolicySha256=$ApprovedRetentionPolicySha256.ToLowerInvariant();verificationArgumentsSha256=$ApprovedVerificationArgumentsSha256.ToLowerInvariant();archiveVerifierSha256=$ApprovedArchiveVerifierSha256.ToLowerInvariant();nextReviewAt=$now.AddDays([int]$policyRecord.reviewIntervalDays).ToString('o');retainUntil=$policyRecord.retainUntil;reviewPublicKeySha256=Get-Sha256 $publicKey;automaticDeletion=$false;containsSecrets=$false}
  try{Write-NewJson $review $record;& $node $helper sign $review $privateKey $reviewSignature;if($LASTEXITCODE-ne0){throw 'Archive-review evidence signing failed'};& $node $helper verify $review $reviewSignature $publicKey;if($LASTEXITCODE-ne0){throw 'Archive-review evidence signature verification failed'}}catch{Remove-Item -LiteralPath $review,$reviewSignature -Force -ErrorAction SilentlyContinue;throw}
}finally{for($index=$streams.Count-1;$index-ge0;$index--){$streams[$index].Dispose()}}
Write-Output "Signed final archive integrity review: $review"
Write-Output "Archive integrity review SHA-256: $(Get-Sha256 $review)"
Write-Output "Next review due: $($record.nextReviewAt)"
