param(
  [Parameter(Mandatory=$true)][string]$EvidenceDirectory,[Parameter(Mandatory=$true)][string]$ArchiveDirectory,
  [Parameter(Mandatory=$true)][string]$ClosureVerifier,[Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,
  [Parameter(Mandatory=$true)][string]$ArchiveSigningPrivateKey,[Parameter(Mandatory=$true)][string]$ArchiveSigningPublicKey,
  [Parameter(Mandatory=$true)][ValidateSet('RECEIVED','EXCEPTION')][string]$ExpectedOutcomeType,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosureVerifierSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosureSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosurePublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerApprovalSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallationReceiptSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedAuditManifestSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyHandoffSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyOutcomeSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$')][string]$ExpectedReleaseId,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$ExpectedReleaseCommit,[Parameter(Mandatory=$true)][string]$ExpectedHost
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Final archive path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Write-NewJson([string]$Path,$Value){$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$bytes=[Text.UTF8Encoding]::new($false).GetBytes(($Value|ConvertTo-Json -Depth 7));$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}
if([string]::IsNullOrWhiteSpace($env:RELEASE_SIGNING_KEY_PASSPHRASE)-or$env:RELEASE_SIGNING_KEY_PASSPHRASE.Length-lt20){throw 'RELEASE_SIGNING_KEY_PASSPHRASE is required for final archive signing'}
$source=[IO.Path]::GetFullPath($EvidenceDirectory).TrimEnd('\');$archive=[IO.Path]::GetFullPath($ArchiveDirectory).TrimEnd('\');$verifier=[IO.Path]::GetFullPath($ClosureVerifier);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper);$privateKey=[IO.Path]::GetFullPath($ArchiveSigningPrivateKey);$publicKey=[IO.Path]::GetFullPath($ArchiveSigningPublicKey)
foreach($path in @($source,$verifier,$node,$helper,$privateKey,$publicKey)){if(-not(Test-Path -LiteralPath $path)){throw "Final archive input not found: $path"};Assert-OrdinaryPath $path}
if(Test-Path -LiteralPath $archive){throw 'Final deployment archive destination must not already exist'}
if($privateKey.StartsWith("$archive\",[StringComparison]::OrdinalIgnoreCase)){throw 'Final archive private key must remain outside the archive'}
$names=@('installer-approval.json','installation-receipt.json','installation-receipt.sig.json','receipt-public.pem','audit-manifest.json','audit-manifest.sig.json','audit-public.pem','custody-handoff.json','custody-handoff.sig.json','sender-public.pem','custody-outcome.json','custody-outcome.sig.json','outcome-public.pem','deployment-closure.json','deployment-closure.sig.json','closure-public.pem')
$items=@(Get-ChildItem -LiteralPath $source -Force);if(@($items|Where-Object{$_.PSIsContainer}).Count-or(@($items.Name|Sort-Object)-join',')-ne(@($names|Sort-Object)-join',')){throw 'Final deployment evidence directory must contain the exact fixed inventory'}
$p=@{};foreach($name in $names){$p[$name]=Join-Path $source $name;Assert-OrdinaryPath $p[$name]}
$verifyArgs=@{ClosurePath=$p['deployment-closure.json'];ClosureSignaturePath=$p['deployment-closure.sig.json'];ClosurePublicKey=$p['closure-public.pem'];InstallerApprovalPath=$p['installer-approval.json'];InstallationReceiptPath=$p['installation-receipt.json'];InstallationReceiptSignaturePath=$p['installation-receipt.sig.json'];ReceiptPublicKey=$p['receipt-public.pem'];AuditManifestPath=$p['audit-manifest.json'];AuditManifestSignaturePath=$p['audit-manifest.sig.json'];AuditPublicKey=$p['audit-public.pem'];CustodyHandoffPath=$p['custody-handoff.json'];CustodyHandoffSignaturePath=$p['custody-handoff.sig.json'];SenderPublicKey=$p['sender-public.pem'];CustodyOutcomePath=$p['custody-outcome.json'];CustodyOutcomeSignaturePath=$p['custody-outcome.sig.json'];OutcomePublicKey=$p['outcome-public.pem'];ExpectedOutcomeType=$ExpectedOutcomeType;NodeExecutable=$node;ReleaseSigningHelper=$helper;ApprovedVerifierSha256=$ApprovedClosureVerifierSha256;ApprovedClosureSha256=$ApprovedClosureSha256;ApprovedClosurePublicKeySha256=$ApprovedClosurePublicKeySha256;ApprovedInstallerApprovalSha256=$ApprovedInstallerApprovalSha256;ApprovedInstallerSha256=$ApprovedInstallerSha256;ApprovedInstallationReceiptSha256=$ApprovedInstallationReceiptSha256;ApprovedAuditManifestSha256=$ApprovedAuditManifestSha256;ApprovedCustodyHandoffSha256=$ApprovedCustodyHandoffSha256;ApprovedCustodyOutcomeSha256=$ApprovedCustodyOutcomeSha256;ApprovedNodeExecutableSha256=$ApprovedNodeExecutableSha256;ApprovedReleaseSigningHelperSha256=$ApprovedReleaseSigningHelperSha256;ExpectedReleaseId=$ExpectedReleaseId;ExpectedReleaseCommit=$ExpectedReleaseCommit;ExpectedHost=$ExpectedHost}
& $verifier @verifyArgs;if($LASTEXITCODE-ne0){throw 'Deployment closure verification failed before final archive creation'}
$nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Final archive requires an authentic OpenJS Foundation Node.js runtime'}
$nodeVersion=(& $node --version|Out-String).Trim()
New-Item -ItemType Directory -Path $archive|Out-Null
try{
  foreach($name in $names){Copy-Item -LiteralPath $p[$name] -Destination (Join-Path $archive $name)}
  Copy-Item -LiteralPath $verifier -Destination (Join-Path $archive 'verify-deployment-closure-record.ps1');Copy-Item -LiteralPath $helper -Destination (Join-Path $archive 'release-signing.mjs');Copy-Item -LiteralPath $publicKey -Destination (Join-Path $archive 'archive-public.pem')
  $files=@(Get-ChildItem -LiteralPath $archive -File|Sort-Object Name|ForEach-Object{[ordered]@{name=$_.Name;sha256=Get-Sha256 $_.FullName}})
  $record=[ordered]@{format='performance-tracker-final-deployment-archive-v1';status='SEALED';createdAt=[DateTimeOffset]::UtcNow.ToString('o');releaseId=$ExpectedReleaseId;releaseCommit=$ExpectedReleaseCommit.ToLowerInvariant();host=$ExpectedHost;custodyOutcomeType=$ExpectedOutcomeType;closureSha256=$ApprovedClosureSha256.ToLowerInvariant();closurePublicKeySha256=$ApprovedClosurePublicKeySha256.ToLowerInvariant();runtime=[ordered]@{version=$nodeVersion;sha256=$ApprovedNodeExecutableSha256.ToLowerInvariant();signer=$nodeSignature.SignerCertificate.Subject;bundled=$false};files=$files;containsSecrets=$false}
  $manifest=Join-Path $archive 'final-archive-manifest.json';$signature=Join-Path $archive 'final-archive-manifest.sig.json';Write-NewJson $manifest $record;& $node $helper sign $manifest $privateKey $signature;if($LASTEXITCODE-ne0){throw 'Final archive manifest signing failed'};& $node $helper verify $manifest $signature (Join-Path $archive 'archive-public.pem');if($LASTEXITCODE-ne0){throw 'Final archive manifest verification failed'}
}catch{Remove-Item -LiteralPath $archive -Recurse -Force -ErrorAction SilentlyContinue;throw}
Write-Output "Portable final deployment archive: $archive"
Write-Output "Final archive manifest SHA-256: $(Get-Sha256 (Join-Path $archive 'final-archive-manifest.json'))"
Write-Output "Final archive public-key SHA-256: $(Get-Sha256 (Join-Path $archive 'archive-public.pem'))"

