$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Split-Path $PSScriptRoot -Parent));$script=Get-Content -LiteralPath (Join-Path $project 'scripts\new-production-installation-receipt.ps1') -Raw;$migration=Get-Content -LiteralPath (Join-Path $project 'scripts\apply-migrations.ps1') -Raw;$iss=Get-Content -LiteralPath (Join-Path $project 'installer\PerformanceTracker.iss') -Raw
function Assert-Match([string]$Value,[string]$Pattern,[string]$Message){if($Value-notmatch$Pattern){throw $Message}}
Assert-Match $migration "format='performance-tracker-migration-evidence-v1'" 'Migrations must emit versioned evidence'
Assert-Match $migration 'GRANT mndf_pms_runtime TO \$ApplicationRole WITH INHERIT TRUE, SET FALSE' 'Application role must inherit runtime access without assuming the runtime identity'
Assert-Match $migration 'databaseUrlsRecorded=\$false' 'Migration evidence must exclude database URLs'
Assert-Match $migration '\[IO.FileMode\]::CreateNew' 'Migration evidence must not overwrite prior evidence'
Assert-Match $iss '\{#ReleaseSource\}\\database\\tests\\\*' 'Installer must include the database verification SQL'
Assert-Match $script 'Production receipt requires an elevated deployment administrator' 'Receipt finalization must require elevation'
Assert-Match $script 'Receipt private key must remain outside the installation root' 'Receipt signing key must remain external'
Assert-Match $script 'Migration evidence fingerprint does not match independent approval' 'Receipt must pin migration evidence'
Assert-Match $script '\$signingHelper verify \$manifest \$manifestSignature \$releaseKey' 'Receipt must verify installed release signature'
Assert-Match $script '\$integrityHelper verify' 'Receipt must verify installed release integrity'
Assert-Match $script 'task is not bound to the installed release' 'Receipt must verify scheduled-task ownership'
Assert-Match $script 'task uses the wrong service account' 'Receipt must verify scheduled-task identity'
Assert-Match $script "task.State-ne'Running'" 'Receipt must require a running application task'
Assert-Match $script '267009' 'Receipt must recognize the Windows task-running result code'
Assert-Match $script 'HealthUrl must use loopback HTTP' 'Receipt health verification must stay local'
Assert-Match $script 'healthBody.ok-ne\$true' 'Receipt must enforce the application health contract'
Assert-Match $script 'verify-production-acls\.ps1' 'Receipt must perform final recursive ACL verification'
Assert-Match $script "format='performance-tracker-production-installation-receipt-v1'" 'Receipt must use a versioned schema'
Assert-Match $script 'containsSecrets=\$false' 'Receipt must be explicitly secret-free'
Assert-Match $script '\[IO.FileMode\]::CreateNew' 'Receipt must never overwrite existing evidence'
Assert-Match $script '\$signingHelper sign \$receipt \$privateKey \$receiptSignature' 'Receipt must be signed'
Assert-Match $script '\$signingHelper verify \$receipt \$receiptSignature \$publicKey' 'Receipt signature must be immediately verified'
Write-Output 'PASS production installation receipt contract'
