$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Split-Path $PSScriptRoot -Parent))
$script=Get-Content -LiteralPath (Join-Path $project 'scripts\complete-staging-rehearsal.ps1') -Raw
function Assert-Match([string]$Pattern,[string]$Message){if($script-notmatch$Pattern){throw $Message}}
Assert-Match 'ConfirmDisposableHostCleanup' 'Cleanup must require explicit disposable-host acknowledgement'
Assert-Match 'ExpectedMachineName-ne\[Environment\]::MachineName' 'Cleanup must bind intent to the exact host'
Assert-Match 'IsInRole\(\[Security\.Principal\.WindowsBuiltInRole\]::Administrator\)' 'Cleanup must require elevation'
Assert-Match 'Refusing to clean a system or production path' 'Cleanup must reject broad and production paths'
Assert-Match 'PerformanceTracker-rehearsal-' 'Cleanup root must use a guarded prefix'
Assert-Match 'CurrentLink must be the guarded current junction directly inside RehearsalRoot' 'Cleanup must restrict the current junction location'
Assert-Match 'CurrentLink target must remain inside the rehearsal releases directory' 'Cleanup must validate the junction target'
Assert-Match 'Evidence trust inputs must be outside RehearsalRoot' 'Cleanup must not delete its active trust inputs'
Assert-Match 'Performance-Tracker-Rehearsal-' 'Cleanup task must use a guarded name'
Assert-Match 'Required rehearsal evidence is missing' 'Cleanup must require complete evidence'
Assert-Match "result.status-ne'PASS'" 'Cleanup must require passed promotion evidence'
Assert-Match 'pre-cleanup-evidence-manifest' 'Evidence must be sealed before cleanup'
Assert-Match 'Rehearsal task is not bound to the approved rehearsal root' 'Cleanup must verify task ownership'
Assert-Match 'Unregister-ScheduledTask' 'Cleanup must remove the rehearsal task'
Assert-Match 'Remove-Item -LiteralPath \$current -Force' 'Cleanup must explicitly remove the verified junction before recursion'
Assert-Match 'Remove-Item -LiteralPath \$root -Recurse -Force' 'Cleanup must remove only the validated root'
Assert-Match 'cleanup-result\.json' 'Cleanup outcome must be recorded'
Assert-Match 'final-evidence-manifest' 'Evidence must be sealed again after cleanup'
Assert-Match 'operatorSid' 'Cleanup evidence must bind the operator SID'
Write-Output 'PASS staging rehearsal cleanup contract'
