param(
  [Parameter(Mandatory=$true)][string]$ClosurePath,[Parameter(Mandatory=$true)][string]$ClosureSignaturePath,[Parameter(Mandatory=$true)][string]$ClosurePublicKey,
  [Parameter(Mandatory=$true)][string]$InstallerApprovalPath,
  [Parameter(Mandatory=$true)][string]$InstallationReceiptPath,[Parameter(Mandatory=$true)][string]$InstallationReceiptSignaturePath,[Parameter(Mandatory=$true)][string]$ReceiptPublicKey,
  [Parameter(Mandatory=$true)][string]$AuditManifestPath,[Parameter(Mandatory=$true)][string]$AuditManifestSignaturePath,[Parameter(Mandatory=$true)][string]$AuditPublicKey,
  [Parameter(Mandatory=$true)][string]$CustodyHandoffPath,[Parameter(Mandatory=$true)][string]$CustodyHandoffSignaturePath,[Parameter(Mandatory=$true)][string]$SenderPublicKey,
  [Parameter(Mandatory=$true)][string]$CustodyOutcomePath,[Parameter(Mandatory=$true)][string]$CustodyOutcomeSignaturePath,[Parameter(Mandatory=$true)][string]$OutcomePublicKey,
  [Parameter(Mandatory=$true)][ValidateSet('RECEIVED','EXCEPTION')][string]$ExpectedOutcomeType,
  [Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedVerifierSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosureSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosurePublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerApprovalSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallationReceiptSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedAuditManifestSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyHandoffSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyOutcomeSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$')][string]$ExpectedReleaseId,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$ExpectedReleaseCommit,[Parameter(Mandatory=$true)][string]$ExpectedHost
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Closure verification path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields,[string]$Label){if((@($Record.PSObject.Properties.Name|Sort-Object)-join',')-ne(@($Fields|Sort-Object)-join',')){throw "$Label schema is incomplete or contains unknown fields"}}
function Read-UtcTimestamp([string]$Value,[string]$Label){try{$parsed=[DateTimeOffset]::ParseExact($Value,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw "$Label must use round-trip UTC format"};if($parsed.Offset-ne[TimeSpan]::Zero-or$parsed-gt[DateTimeOffset]::UtcNow.AddMinutes(5)){throw "$Label is not a valid UTC time"};$parsed}
$verifier=[IO.Path]::GetFullPath($MyInvocation.MyCommand.Path);$closure=[IO.Path]::GetFullPath($ClosurePath);$closureSignature=[IO.Path]::GetFullPath($ClosureSignaturePath);$closureKey=[IO.Path]::GetFullPath($ClosurePublicKey);$approval=[IO.Path]::GetFullPath($InstallerApprovalPath);$receipt=[IO.Path]::GetFullPath($InstallationReceiptPath);$receiptSignature=[IO.Path]::GetFullPath($InstallationReceiptSignaturePath);$receiptKey=[IO.Path]::GetFullPath($ReceiptPublicKey);$manifest=[IO.Path]::GetFullPath($AuditManifestPath);$manifestSignature=[IO.Path]::GetFullPath($AuditManifestSignaturePath);$auditKey=[IO.Path]::GetFullPath($AuditPublicKey);$handoff=[IO.Path]::GetFullPath($CustodyHandoffPath);$handoffSignature=[IO.Path]::GetFullPath($CustodyHandoffSignaturePath);$senderKey=[IO.Path]::GetFullPath($SenderPublicKey);$outcome=[IO.Path]::GetFullPath($CustodyOutcomePath);$outcomeSignature=[IO.Path]::GetFullPath($CustodyOutcomeSignaturePath);$outcomeKey=[IO.Path]::GetFullPath($OutcomePublicKey);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper)
$inputs=@($verifier,$closure,$closureSignature,$closureKey,$approval,$receipt,$receiptSignature,$receiptKey,$manifest,$manifestSignature,$auditKey,$handoff,$handoffSignature,$senderKey,$outcome,$outcomeSignature,$outcomeKey,$node,$helper);$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Closure verification input not found: $path"};Assert-OrdinaryPath $path;$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  $approved=@{$verifier=$ApprovedVerifierSha256;$closure=$ApprovedClosureSha256;$closureKey=$ApprovedClosurePublicKeySha256;$approval=$ApprovedInstallerApprovalSha256;$receipt=$ApprovedInstallationReceiptSha256;$manifest=$ApprovedAuditManifestSha256;$handoff=$ApprovedCustodyHandoffSha256;$outcome=$ApprovedCustodyOutcomeSha256;$node=$ApprovedNodeExecutableSha256;$helper=$ApprovedReleaseSigningHelperSha256}
  foreach($name in $approved.Keys){$path=Get-Variable -Name $name -ValueOnly;if((Get-Sha256 $path)-ne$approved[$name].ToLowerInvariant()){throw "Approved $name fingerprint does not match closure evidence"}}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Closure verification requires an authentic OpenJS Foundation Node.js runtime'}
  foreach($triple in @(@($closure,$closureSignature,$closureKey),@($receipt,$receiptSignature,$receiptKey),@($manifest,$manifestSignature,$auditKey),@($handoff,$handoffSignature,$senderKey),@($outcome,$outcomeSignature,$outcomeKey))){& $node $helper verify $triple[0] $triple[1] $triple[2];if($LASTEXITCODE-ne0){throw 'Deployment closure evidence signature verification failed'}}
  try{$closureRecord=Get-Content $closure -Raw|ConvertFrom-Json;$approvalRecord=Get-Content $approval -Raw|ConvertFrom-Json;$receiptRecord=Get-Content $receipt -Raw|ConvertFrom-Json;$manifestRecord=Get-Content $manifest -Raw|ConvertFrom-Json;$handoffRecord=Get-Content $handoff -Raw|ConvertFrom-Json;$outcomeRecord=Get-Content $outcome -Raw|ConvertFrom-Json}catch{throw 'Deployment closure evidence is not valid JSON'}
  Assert-ExactSchema $closureRecord @('format','status','closedAt','closedBySid','releaseId','releaseCommit','host','installerSha256','installerApprovalSha256','installationReceiptSha256','auditManifestSha256','custodyHandoffSha256','custodyTransferId','custodyOutcomeType','custodyOutcomeSha256','closurePublicKeySha256','containsSecrets') 'Deployment closure'
  Assert-ExactSchema $approvalRecord @('format','approvedBySid','approvedAtUtc','expiresAtUtc','installerSha256','signingCertificateThumbprint','timestampCertificateThumbprint','version','releaseCommit','releaseId','compilerSha256','signToolSha256','releasePublicKeySha256','nodeRuntimeSha256','launcherSha256','verifierSha256','aclHelperSha256','releaseSigningHelperSha256','packageCustodians') 'Installer approval'
  Assert-ExactSchema $receiptRecord @('format','status','completedAt','host','operatorSid','releaseId','releaseCommit','releaseManifestSha256','migrationEvidenceSha256','applicationTaskName','applicationTaskState','serviceAccountSid','healthStatus','healthEndpoint','aclVerificationSha256','receiptPublicKeySha256','containsSecrets') 'Installation receipt'
  Assert-ExactSchema $manifestRecord @('format','status','createdAt','releaseId','releaseCommit','host','receiptSha256','receiptPublicKeySha256','runtime','files','containsSecrets') 'Audit manifest'
  Assert-ExactSchema $handoffRecord @('format','status','transferId','handedOffAt','senderSid','receiverSid','transferMethod','manifestSha256','bundlePublicKeySha256','releaseId','releaseCommit','host','custodyPublicKeySha256','containsSecrets') 'Custody handoff'
  $outcomeFields=if($ExpectedOutcomeType-eq'RECEIVED'){@('format','status','transferId','receivedAt','senderSid','receiverSid','transferMethod','handoffSha256','manifestSha256','bundleVerified','releaseId','releaseCommit','host','receiverPublicKeySha256','containsSecrets')}else{@('format','status','transferId','exceptionAt','handedOffAt','acknowledgementHours','dueAt','reason','authorizedCustodianSid','senderSid','receiverSid','transferMethod','handoffSha256','manifestSha256','releaseId','releaseCommit','host','exceptionPublicKeySha256','receiptPresent','containsSecrets')};Assert-ExactSchema $outcomeRecord $outcomeFields 'Custody outcome'
  if($closureRecord.format-ne'performance-tracker-deployment-closure-v1'-or$closureRecord.status-ne'CLOSED'-or$closureRecord.containsSecrets-ne$false-or([string]$closureRecord.closedBySid)-notmatch'^S-1-(?:\d+-)*\d+$'){throw 'Deployment closure is not a valid redacted record'};[void](Read-UtcTimestamp ([string]$closureRecord.closedAt) 'Closure timestamp')
  $expectedOutcomeFormat=if($ExpectedOutcomeType-eq'RECEIVED'){'performance-tracker-audit-custody-receipt-v1'}else{'performance-tracker-audit-custody-exception-v1'}
  if($approvalRecord.format-ne'performance-tracker-install-approval-v1'-or$receiptRecord.format-ne'performance-tracker-production-installation-receipt-v1'-or$receiptRecord.status-ne'PASS'-or$manifestRecord.format-ne'performance-tracker-installation-audit-bundle-v1'-or$manifestRecord.status-ne'PASS'-or$handoffRecord.format-ne'performance-tracker-audit-custody-handoff-v1'-or$handoffRecord.status-ne'HANDED_OFF'-or$outcomeRecord.format-ne$expectedOutcomeFormat-or$outcomeRecord.status-ne$ExpectedOutcomeType){throw 'Closure evidence does not contain the required passed lifecycle records'}
  foreach($record in @($closureRecord,$approvalRecord,$receiptRecord,$manifestRecord,$handoffRecord,$outcomeRecord)){if($record.releaseId-ne$ExpectedReleaseId-or$record.releaseCommit-ne$ExpectedReleaseCommit.ToLowerInvariant()){throw 'Closure evidence belongs to another release'}};foreach($record in @($closureRecord,$receiptRecord,$manifestRecord,$handoffRecord,$outcomeRecord)){if($record.host-ne$ExpectedHost){throw 'Closure evidence belongs to another host'}}
  if($approvalRecord.installerSha256-ne$ApprovedInstallerSha256.ToLowerInvariant()-or$closureRecord.installerSha256-ne$ApprovedInstallerSha256.ToLowerInvariant()-or$closureRecord.installerApprovalSha256-ne$ApprovedInstallerApprovalSha256.ToLowerInvariant()-or$closureRecord.installationReceiptSha256-ne$ApprovedInstallationReceiptSha256.ToLowerInvariant()-or$closureRecord.auditManifestSha256-ne$ApprovedAuditManifestSha256.ToLowerInvariant()-or$closureRecord.custodyHandoffSha256-ne$ApprovedCustodyHandoffSha256.ToLowerInvariant()-or$closureRecord.custodyOutcomeSha256-ne$ApprovedCustodyOutcomeSha256.ToLowerInvariant()-or$closureRecord.closurePublicKeySha256-ne$ApprovedClosurePublicKeySha256.ToLowerInvariant()){throw 'Deployment closure does not bind the independently approved evidence'}
  if($manifestRecord.receiptSha256-ne$ApprovedInstallationReceiptSha256.ToLowerInvariant()-or$handoffRecord.manifestSha256-ne$ApprovedAuditManifestSha256.ToLowerInvariant()-or$outcomeRecord.manifestSha256-ne$ApprovedAuditManifestSha256.ToLowerInvariant()-or$outcomeRecord.handoffSha256-ne$ApprovedCustodyHandoffSha256.ToLowerInvariant()-or$outcomeRecord.transferId-ne$handoffRecord.transferId-or$closureRecord.custodyTransferId-ne$handoffRecord.transferId-or$closureRecord.custodyOutcomeType-ne$ExpectedOutcomeType){throw 'Deployment closure evidence chain is not internally linked'}
  if($ExpectedOutcomeType-eq'RECEIVED'-and$outcomeRecord.bundleVerified-ne$true){throw 'Received closure outcome did not verify the bundle'};if($ExpectedOutcomeType-eq'EXCEPTION'-and$outcomeRecord.receiptPresent-ne$false){throw 'Exception closure outcome conflicts with a receipt'}
}finally{for($index=$streams.Count-1;$index-ge0;$index--){$streams[$index].Dispose()}}
Write-Output "Deployment closure verified: $($ApprovedClosureSha256.ToLowerInvariant())"
Write-Output "Release: $ExpectedReleaseId ($($ExpectedReleaseCommit.ToLowerInvariant()))"

