param(
  [Parameter(Mandatory=$true)][string]$HandoffPath,[Parameter(Mandatory=$true)][string]$HandoffSignaturePath,[Parameter(Mandatory=$true)][string]$SenderPublicKey,
  [Parameter(Mandatory=$true)][string]$ExceptionPath,[Parameter(Mandatory=$true)][string]$ExceptionSignaturePath,[Parameter(Mandatory=$true)][string]$ExceptionPublicKey,
  [Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ReleaseSigningHelper,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedVerifierSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedHandoffSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedExceptionSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedSenderPublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedExceptionPublicKeySha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedReleaseSigningHelperSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ExpectedManifestSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^S-1-(?:\d+-)*\d+$')][string]$ExpectedSenderSid,[Parameter(Mandatory=$true)][ValidatePattern('^S-1-(?:\d+-)*\d+$')][string]$ExpectedReceiverSid,
  [Parameter(Mandatory=$true)][ValidatePattern('^S-1-(?:\d+-)*\d+$')][string[]]$ApprovedCustodianSids,[Parameter(Mandatory=$true)][ValidateSet('OFFLINE_ENCRYPTED_MEDIA','SECURE_MANAGED_SHARE','PHYSICAL_CUSTODY')][string]$ExpectedTransferMethod,
  [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$')][string]$ExpectedReleaseId,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$ExpectedReleaseCommit,[Parameter(Mandatory=$true)][string]$ExpectedHost
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Custody exception verification path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields,[string]$Label){$actual=@($Record.PSObject.Properties.Name|Sort-Object)-join',';$expected=@($Fields|Sort-Object)-join',';if($actual-ne$expected){throw "$Label schema is incomplete or contains unknown fields"}}
function Read-UtcTimestamp([string]$Value,[string]$Label){try{$parsed=[DateTimeOffset]::ParseExact($Value,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw "$Label must use round-trip UTC format"};if($parsed.Offset-ne[TimeSpan]::Zero-or$parsed-gt[DateTimeOffset]::UtcNow.AddMinutes(5)){throw "$Label is not a valid UTC time"};$parsed}
$verifier=[IO.Path]::GetFullPath($MyInvocation.MyCommand.Path);$handoff=[IO.Path]::GetFullPath($HandoffPath);$handoffSignature=[IO.Path]::GetFullPath($HandoffSignaturePath);$senderKey=[IO.Path]::GetFullPath($SenderPublicKey);$exception=[IO.Path]::GetFullPath($ExceptionPath);$exceptionSignature=[IO.Path]::GetFullPath($ExceptionSignaturePath);$exceptionKey=[IO.Path]::GetFullPath($ExceptionPublicKey);$node=[IO.Path]::GetFullPath($NodeExecutable);$helper=[IO.Path]::GetFullPath($ReleaseSigningHelper)
$inputs=@($verifier,$handoff,$handoffSignature,$senderKey,$exception,$exceptionSignature,$exceptionKey,$node,$helper);$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Custody exception verification input not found: $path"};Assert-OrdinaryPath $path;$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  $approved=@{$verifier=$ApprovedVerifierSha256;$handoff=$ApprovedHandoffSha256;$exception=$ApprovedExceptionSha256;$senderKey=$ApprovedSenderPublicKeySha256;$exceptionKey=$ApprovedExceptionPublicKeySha256;$node=$ApprovedNodeExecutableSha256;$helper=$ApprovedReleaseSigningHelperSha256}
  foreach($name in $approved.Keys){$path=Get-Variable -Name $name -ValueOnly;if((Get-Sha256 $path)-ne$approved[$name].ToLowerInvariant()){throw "Approved $name fingerprint does not match custody exception evidence"}}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Custody exception verification requires an authentic OpenJS Foundation Node.js runtime'}
  & $node $helper verify $handoff $handoffSignature $senderKey;if($LASTEXITCODE-ne0){throw 'Sender custody signature verification failed'};& $node $helper verify $exception $exceptionSignature $exceptionKey;if($LASTEXITCODE-ne0){throw 'Custody exception signature verification failed'}
  try{$handoffRecord=Get-Content -LiteralPath $handoff -Raw|ConvertFrom-Json;$exceptionRecord=Get-Content -LiteralPath $exception -Raw|ConvertFrom-Json}catch{throw 'Custody exception evidence is not valid JSON'}
  Assert-ExactSchema $handoffRecord @('format','status','transferId','handedOffAt','senderSid','receiverSid','transferMethod','manifestSha256','bundlePublicKeySha256','releaseId','releaseCommit','host','custodyPublicKeySha256','containsSecrets') 'Custody handoff'
  Assert-ExactSchema $exceptionRecord @('format','status','transferId','exceptionAt','handedOffAt','acknowledgementHours','dueAt','reason','authorizedCustodianSid','senderSid','receiverSid','transferMethod','handoffSha256','manifestSha256','releaseId','releaseCommit','host','exceptionPublicKeySha256','receiptPresent','containsSecrets') 'Custody exception'
  if($handoffRecord.format-ne'performance-tracker-audit-custody-handoff-v1'-or$handoffRecord.status-ne'HANDED_OFF'-or$handoffRecord.containsSecrets-ne$false){throw 'Custody handoff is not a valid redacted record'}
  if($exceptionRecord.format-ne'performance-tracker-audit-custody-exception-v1'-or$exceptionRecord.status-ne'EXCEPTION'-or$exceptionRecord.containsSecrets-ne$false-or$exceptionRecord.receiptPresent-ne$false){throw 'Custody exception is not a valid redacted terminal outcome'}
  $reasons=@('ACKNOWLEDGEMENT_OVERDUE','RECEIVER_UNAVAILABLE','TRANSFER_MEDIA_LOST','TRANSFER_CANCELLED');if($exceptionRecord.reason-notin$reasons){throw 'Custody exception reason is not approved'}
  if([int]$exceptionRecord.acknowledgementHours-lt1-or[int]$exceptionRecord.acknowledgementHours-gt720){throw 'Custody acknowledgement window is outside approved bounds'}
  $handedOffAt=Read-UtcTimestamp ([string]$handoffRecord.handedOffAt) 'Handoff timestamp';$exceptionAt=Read-UtcTimestamp ([string]$exceptionRecord.exceptionAt) 'Exception timestamp';$dueAt=Read-UtcTimestamp ([string]$exceptionRecord.dueAt) 'Custody due timestamp'
  if($exceptionAt-lt$handedOffAt-or$dueAt-ne$handedOffAt.AddHours([int]$exceptionRecord.acknowledgementHours)-or($exceptionRecord.reason-eq'ACKNOWLEDGEMENT_OVERDUE'-and$exceptionAt-lt$dueAt)){throw 'Custody exception chronology or deadline is invalid'}
  $custodians=@($ApprovedCustodianSids|Sort-Object -Unique);if($custodians.Count-ne$ApprovedCustodianSids.Count-or$exceptionRecord.authorizedCustodianSid-notin$custodians){throw 'Custody exception signer is not independently approved'}
  if($handoffRecord.transferId-ne$exceptionRecord.transferId-or$handoffRecord.senderSid-ne$exceptionRecord.senderSid-or$handoffRecord.receiverSid-ne$exceptionRecord.receiverSid-or$handoffRecord.transferMethod-ne$exceptionRecord.transferMethod-or$handoffRecord.handedOffAt-ne$exceptionRecord.handedOffAt){throw 'Custody exception does not match its handoff'}
  if($handoffRecord.senderSid-ne$ExpectedSenderSid-or$handoffRecord.receiverSid-ne$ExpectedReceiverSid-or$handoffRecord.transferMethod-ne$ExpectedTransferMethod-or$handoffRecord.manifestSha256-ne$ExpectedManifestSha256.ToLowerInvariant()-or$exceptionRecord.manifestSha256-ne$ExpectedManifestSha256.ToLowerInvariant()){throw 'Custody exception does not match independent transfer approval'}
  if($exceptionRecord.handoffSha256-ne$ApprovedHandoffSha256.ToLowerInvariant()-or$handoffRecord.custodyPublicKeySha256-ne$ApprovedSenderPublicKeySha256.ToLowerInvariant()-or$exceptionRecord.exceptionPublicKeySha256-ne$ApprovedExceptionPublicKeySha256.ToLowerInvariant()){throw 'Custody exception is not bound to the approved handoff and keys'}
  foreach($record in @($handoffRecord,$exceptionRecord)){if($record.releaseId-ne$ExpectedReleaseId-or$record.releaseCommit-ne$ExpectedReleaseCommit.ToLowerInvariant()-or$record.host-ne$ExpectedHost){throw 'Custody exception evidence belongs to another deployment'}}
}finally{for($index=$streams.Count-1;$index-ge0;$index--){$streams[$index].Dispose()}}
Write-Output "Audit bundle custody exception verified: $($exceptionRecord.transferId)"
Write-Output "Exception: $($ApprovedExceptionSha256.ToLowerInvariant())"

