param(
  [Parameter(Mandatory=$true)][string]$ArchiveDirectory,[Parameter(Mandatory=$true)][string]$NodeExecutable,[Parameter(Mandatory=$true)][string]$ExternalReleaseSigningHelper,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedVerifierSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedManifestSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedArchivePublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedNodeExecutableSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedExternalSigningHelperSha256,
  [Parameter(Mandatory=$true)][ValidateSet('RECEIVED','EXCEPTION')][string]$ExpectedOutcomeType,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosureSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedClosurePublicKeySha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerApprovalSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallerSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedInstallationReceiptSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedAuditManifestSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyHandoffSha256,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ApprovedCustodyOutcomeSha256,
  [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$')][string]$ExpectedReleaseId,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$ExpectedReleaseCommit,[Parameter(Mandatory=$true)][string]$ExpectedHost
)
$ErrorActionPreference='Stop'
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert-OrdinaryPath([string]$Path){$current=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;while($current){if(($current.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw "Final archive verification path contains a reparse point: $($current.FullName)"};$parent=[IO.Path]::GetDirectoryName($current.FullName);if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$current.FullName){break};$current=Get-Item -LiteralPath $parent -Force -ErrorAction Stop}}
function Assert-ExactSchema($Record,[string[]]$Fields,[string]$Label){if((@($Record.PSObject.Properties.Name|Sort-Object)-join',')-ne(@($Fields|Sort-Object)-join',')){throw "$Label schema is incomplete or contains unknown fields"}}
function Read-UtcTimestamp([string]$Value){try{$parsed=[DateTimeOffset]::ParseExact($Value,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw 'Final archive timestamp must use round-trip UTC format'};if($parsed.Offset-ne[TimeSpan]::Zero-or$parsed-gt[DateTimeOffset]::UtcNow.AddMinutes(5)){throw 'Final archive timestamp is not a valid UTC time'};$parsed}
$self=[IO.Path]::GetFullPath($MyInvocation.MyCommand.Path);$archive=[IO.Path]::GetFullPath($ArchiveDirectory).TrimEnd('\');$node=[IO.Path]::GetFullPath($NodeExecutable);$externalHelper=[IO.Path]::GetFullPath($ExternalReleaseSigningHelper)
foreach($path in @($self,$archive,$node,$externalHelper)){if(-not(Test-Path -LiteralPath $path)){throw "Final archive verification input not found: $path"};Assert-OrdinaryPath $path}
foreach($path in @($self,$node,$externalHelper)){if($path.StartsWith("$archive\",[StringComparison]::OrdinalIgnoreCase)){throw 'Initial verifier, Node.js and signing helper trust inputs must remain outside the archive'}}
$payloadNames=@('archive-public.pem','audit-manifest.json','audit-manifest.sig.json','audit-public.pem','closure-public.pem','custody-handoff.json','custody-handoff.sig.json','custody-outcome.json','custody-outcome.sig.json','deployment-closure.json','deployment-closure.sig.json','installation-receipt.json','installation-receipt.sig.json','installer-approval.json','outcome-public.pem','receipt-public.pem','release-signing.mjs','sender-public.pem','verify-deployment-closure-record.ps1')
$allNames=@($payloadNames+'final-archive-manifest.json'+'final-archive-manifest.sig.json');$items=@(Get-ChildItem -LiteralPath $archive -Force)
if(@($items|Where-Object{$_.PSIsContainer}).Count-or(@($items.Name|Sort-Object)-join',')-ne(@($allNames|Sort-Object)-join',')){throw 'Final deployment archive must contain the exact fixed inventory'}
$p=@{};foreach($name in $allNames){$p[$name]=Join-Path $archive $name;Assert-OrdinaryPath $p[$name]}
$inputs=@($self,$node,$externalHelper)+@($allNames|ForEach-Object{$p[$_]});$streams=[Collections.Generic.List[IO.FileStream]]::new()
try{
  foreach($path in $inputs){$streams.Add([IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read))}
  if((Get-Sha256 $self)-ne$ApprovedVerifierSha256.ToLowerInvariant()){throw 'Approved archive verifier fingerprint does not match'}
  if((Get-Sha256 $node)-ne$ApprovedNodeExecutableSha256.ToLowerInvariant()){throw 'Approved Node.js fingerprint does not match'}
  if((Get-Sha256 $externalHelper)-ne$ApprovedExternalSigningHelperSha256.ToLowerInvariant()){throw 'Approved external signing-helper fingerprint does not match'}
  if((Get-Sha256 $p['final-archive-manifest.json'])-ne$ApprovedManifestSha256.ToLowerInvariant()){throw 'Approved final archive manifest fingerprint does not match'}
  if((Get-Sha256 $p['archive-public.pem'])-ne$ApprovedArchivePublicKeySha256.ToLowerInvariant()){throw 'Approved final archive public-key fingerprint does not match'}
  $nodeSignature=Get-AuthenticodeSignature -LiteralPath $node;if($nodeSignature.Status-ne'Valid'-or$nodeSignature.SignerCertificate.Subject-notmatch'(^|,\s*)O=OpenJS Foundation(,|$)'){throw 'Final archive verification requires an authentic OpenJS Foundation Node.js runtime'}
  & $node $externalHelper verify $p['final-archive-manifest.json'] $p['final-archive-manifest.sig.json'] $p['archive-public.pem'];if($LASTEXITCODE-ne0){throw 'Final archive manifest signature verification failed'}
  try{$record=Get-Content -LiteralPath $p['final-archive-manifest.json'] -Raw|ConvertFrom-Json}catch{throw 'Final archive manifest is not valid JSON'}
  Assert-ExactSchema $record @('format','status','createdAt','releaseId','releaseCommit','host','custodyOutcomeType','closureSha256','closurePublicKeySha256','runtime','files','containsSecrets') 'Final archive manifest';Assert-ExactSchema $record.runtime @('version','sha256','signer','bundled') 'Final archive runtime'
  if($record.format-ne'performance-tracker-final-deployment-archive-v1'-or$record.status-ne'SEALED'-or$record.containsSecrets-ne$false-or$record.runtime.bundled-ne$false){throw 'Final archive manifest is not a sealed, redacted external-runtime record'};[void](Read-UtcTimestamp ([string]$record.createdAt))
  if($record.releaseId-ne$ExpectedReleaseId-or$record.releaseCommit-ne$ExpectedReleaseCommit.ToLowerInvariant()-or$record.host-ne$ExpectedHost-or$record.custodyOutcomeType-ne$ExpectedOutcomeType){throw 'Final archive belongs to another deployment'}
  if($record.closureSha256-ne$ApprovedClosureSha256.ToLowerInvariant()-or$record.closurePublicKeySha256-ne$ApprovedClosurePublicKeySha256.ToLowerInvariant()){throw 'Final archive closure trust does not match independent approval'}
  $nodeVersion=(& $node --version|Out-String).Trim();if($record.runtime.sha256-ne$ApprovedNodeExecutableSha256.ToLowerInvariant()-or$record.runtime.version-ne$nodeVersion-or$record.runtime.signer-ne$nodeSignature.SignerCertificate.Subject){throw 'Final archive runtime identity does not match the approved external runtime'}
  $listed=@($record.files);if($listed.Count-ne$payloadNames.Count-or(@($listed.name|Sort-Object)-join',')-ne(@($payloadNames|Sort-Object)-join',')){throw 'Final archive manifest inventory is incomplete or contains unknown files'}
  foreach($entry in $listed){Assert-ExactSchema $entry @('name','sha256') 'Final archive file entry';if(([string]$entry.name)-notin$payloadNames-or([string]$entry.sha256)-notmatch'^[0-9a-f]{64}$'-or(Get-Sha256 $p[[string]$entry.name])-ne$entry.sha256){throw "Final archive content fingerprint mismatch: $($entry.name)"}}
  $closureVerifier=$p['verify-deployment-closure-record.ps1'];$enclosedHelper=$p['release-signing.mjs']
  $verifyArgs=@{ClosurePath=$p['deployment-closure.json'];ClosureSignaturePath=$p['deployment-closure.sig.json'];ClosurePublicKey=$p['closure-public.pem'];InstallerApprovalPath=$p['installer-approval.json'];InstallationReceiptPath=$p['installation-receipt.json'];InstallationReceiptSignaturePath=$p['installation-receipt.sig.json'];ReceiptPublicKey=$p['receipt-public.pem'];AuditManifestPath=$p['audit-manifest.json'];AuditManifestSignaturePath=$p['audit-manifest.sig.json'];AuditPublicKey=$p['audit-public.pem'];CustodyHandoffPath=$p['custody-handoff.json'];CustodyHandoffSignaturePath=$p['custody-handoff.sig.json'];SenderPublicKey=$p['sender-public.pem'];CustodyOutcomePath=$p['custody-outcome.json'];CustodyOutcomeSignaturePath=$p['custody-outcome.sig.json'];OutcomePublicKey=$p['outcome-public.pem'];ExpectedOutcomeType=$ExpectedOutcomeType;NodeExecutable=$node;ReleaseSigningHelper=$enclosedHelper;ApprovedVerifierSha256=(Get-Sha256 $closureVerifier);ApprovedClosureSha256=$ApprovedClosureSha256;ApprovedClosurePublicKeySha256=$ApprovedClosurePublicKeySha256;ApprovedInstallerApprovalSha256=$ApprovedInstallerApprovalSha256;ApprovedInstallerSha256=$ApprovedInstallerSha256;ApprovedInstallationReceiptSha256=$ApprovedInstallationReceiptSha256;ApprovedAuditManifestSha256=$ApprovedAuditManifestSha256;ApprovedCustodyHandoffSha256=$ApprovedCustodyHandoffSha256;ApprovedCustodyOutcomeSha256=$ApprovedCustodyOutcomeSha256;ApprovedNodeExecutableSha256=$ApprovedNodeExecutableSha256;ApprovedReleaseSigningHelperSha256=(Get-Sha256 $enclosedHelper);ExpectedReleaseId=$ExpectedReleaseId;ExpectedReleaseCommit=$ExpectedReleaseCommit;ExpectedHost=$ExpectedHost}
  & $closureVerifier @verifyArgs
  Write-Output "Verified final deployment archive: $archive"
}finally{foreach($stream in $streams){$stream.Dispose()}}
