import { withTenantTransaction } from "@/lib/auth/repository";

export async function loadRecordsGovernance(tenantId:string,accountId:string){return withTenantTransaction(tenantId,accountId,async c=>{
 const[policies,holds,exports,disposals]=await Promise.all([
  c.query("SELECT * FROM retention_policy_versions WHERE tenant_id=$1 ORDER BY record_class,version_no DESC",[tenantId]),
  c.query("SELECT * FROM legal_holds WHERE tenant_id=$1 ORDER BY created_at DESC",[tenantId]),
  c.query("SELECT * FROM controlled_export_requests WHERE tenant_id=$1 ORDER BY requested_at DESC LIMIT 100",[tenantId]),
  c.query("SELECT r.*,COALESCE(jsonb_agg(a ORDER BY a.approved_at)FILTER(WHERE a.id IS NOT NULL),'[]')approvals FROM record_disposal_requests r LEFT JOIN record_disposal_approvals a ON a.tenant_id=r.tenant_id AND a.disposal_request_id=r.id WHERE r.tenant_id=$1 GROUP BY r.tenant_id,r.id ORDER BY r.requested_at DESC",[tenantId])]);
 return{policies:policies.rows,legalHolds:holds.rows,exportRequests:exports.rows,disposalRequests:disposals.rows};
})}

export async function createRetentionPolicy(t:string,a:string,input:{recordClass:string;retainIndefinitely:boolean;retentionDays?:number;reason:string}){return withTenantTransaction(t,a,async c=>(await c.query(`INSERT INTO retention_policy_versions(tenant_id,record_class,version_no,retain_indefinitely,retention_days,policy_reason,created_by_account_id)VALUES($1,$2,(SELECT COALESCE(max(version_no),0)+1 FROM retention_policy_versions WHERE tenant_id=$1 AND record_class=$2),$3,$4,$5,$6)RETURNING *`,[t,input.recordClass,input.retainIndefinitely,input.retainIndefinitely?null:input.retentionDays,input.reason,a])).rows[0])}
export async function approveRetentionPolicy(t:string,a:string,id:string){return withTenantTransaction(t,a,async c=>{const draft=(await c.query("SELECT record_class FROM retention_policy_versions WHERE tenant_id=$1 AND id=$2 AND status='DRAFT'",[t,id])).rows[0];if(!draft)throw new Error("Draft retention policy not found");await c.query("UPDATE retention_policy_versions SET status='RETIRED',retired_at=clock_timestamp()WHERE tenant_id=$1 AND record_class=$2 AND status='APPROVED'",[t,draft.record_class]);return(await c.query("UPDATE retention_policy_versions SET status='APPROVED'WHERE tenant_id=$1 AND id=$2 RETURNING *",[t,id])).rows[0]})}
export async function createLegalHold(t:string,a:string,input:{scopeType:string;scopeId?:string;reason:string}){return withTenantTransaction(t,a,async c=>(await c.query("INSERT INTO legal_holds(tenant_id,scope_type,scope_id,reason,created_by_account_id)VALUES($1,$2,$3,$4,$5)RETURNING *",[t,input.scopeType,input.scopeId??null,input.reason,a])).rows[0])}
export async function releaseLegalHold(t:string,a:string,id:string,reason:string){return withTenantTransaction(t,a,async c=>(await c.query("UPDATE legal_holds SET released_by_account_id=$3,released_at=clock_timestamp(),release_reason=$4 WHERE tenant_id=$1 AND id=$2 AND released_at IS NULL RETURNING *",[t,id,a,reason])).rows[0])}
export async function requestControlledExport(t:string,a:string,input:{exportScope:string;scopeId?:string;purpose:string}){return withTenantTransaction(t,a,async c=>(await c.query("INSERT INTO controlled_export_requests(tenant_id,export_scope,scope_id,purpose,requested_by_account_id)VALUES($1,$2,$3,$4,$5)RETURNING *",[t,input.exportScope,input.scopeId??null,input.purpose,a])).rows[0])}
export async function decideControlledExport(t:string,a:string,id:string,approved:boolean,reason:string){return withTenantTransaction(t,a,async c=>(await c.query("UPDATE controlled_export_requests SET status=$3,decided_by_account_id=$4,decided_at=clock_timestamp(),decision_reason=$5,expires_at=CASE WHEN $3='APPROVED'THEN clock_timestamp()+interval'24 hours'END WHERE tenant_id=$1 AND id=$2 AND status='REQUESTED'AND requested_by_account_id<>$4 RETURNING *",[t,id,approved?'APPROVED':'REJECTED',a,reason])).rows[0])}
export async function requestDisposal(t:string,a:string,input:{recordClass:string;cutoffAt:string;reason:string}){return withTenantTransaction(t,a,async c=>(await c.query("INSERT INTO record_disposal_requests(tenant_id,record_class,cutoff_at,reason,requested_by_account_id)VALUES($1,$2,$3,$4,$5)RETURNING *",[t,input.recordClass,input.cutoffAt,input.reason,a])).rows[0])}
export async function approveDisposal(t:string,a:string,id:string,authorityRole:string,reason:string){return withTenantTransaction(t,a,async c=>(await c.query("INSERT INTO record_disposal_approvals(tenant_id,disposal_request_id,authority_role,approved_by_account_id,reason)VALUES($1,$2,$3,$4,$5)RETURNING *",[t,id,authorityRole,a,reason])).rows[0])}

